Set Shell zsh
Sleep 2.5s
Type "sekrt add"
Enter
Sleep 1s
Type "bbadjustt"
Enter
Escape
Type "[I"
Escape
Type "[?2026;2$y"
Sleep 500ms
Type "work/"
Sleep 500ms
Type "openai"
Sleep 500ms
Escape
Type "[B"
Sleep 500ms
Escape
Type "[C"
Sleep 1s
Escape
Type "[B"
Escape
Type "[A"
Sleep 500ms
Escape
Type "[Busername"
Sleep 500ms
Escape
Type "[B"
Escape
Type "[200~MY_OPENAI_API_KEY_35982v3cmhrutny3829cnmqhunow93f5inwhnh89f943852nv"
Escape
Type "[201~"
Enter
Sleep 4.5s

